const API=localStorage.getItem('apiBase')||'http://localhost:8080/api';let token=localStorage.getItem('dt_token')||'';let demo=localStorage.getItem('dt_demo')==='true';let projects=[];
const demoProjects=[
{id:1,equipoId:1,titulo:'Cuidemos nuestros espacios comunes',descripcion:'Propuesta para mejorar el cuidado de salones y patios.',problemaInicial:'Poco cuidado de los espacios comunes.',estado:'EN_PROCESO',progreso:60},
{id:2,equipoId:1,titulo:'Patio escolar sostenible',descripcion:'Ideas para convertir el patio en un espacio más limpio.',problemaInicial:'Acumulación de residuos.',estado:'EN_PROCESO',progreso:35},
{id:3,equipoId:2,titulo:'Aulas más organizadas',descripcion:'Diseño de hábitos para mantener las aulas organizadas.',problemaInicial:'Desorden en los salones.',estado:'FINALIZADO',progreso:100}];
const stages=[['EMPATIZAR','Comprender a estudiantes y comunidad mediante observación, entrevistas y encuestas.'],['DEFINIR','Sintetizar hallazgos y formular el problema y reto de diseño.'],['IDEAR','Generar alternativas y seleccionar soluciones con mayor potencial.'],['PROTOTIPAR','Construir una primera versión de la solución.'],['PROBAR','Probar con usuarios, medir resultados y mejorar.']];
const $=s=>document.querySelector(s);
async function api(path,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})};if(token)headers.Authorization='Bearer '+token;const r=await fetch(API+path,{...opt,headers});if(!r.ok)throw Error(await r.text());return r.status===204?null:r.json()}
function section(n){document.querySelectorAll('.section').forEach(x=>x.classList.add('hidden'));$('#'+n).classList.remove('hidden');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.section===n));$('#title').textContent={dashboard:'Dashboard',proyectos:'Mis proyectos',etapas:'Etapas',evidencias:'Evidencias'}[n];if(n==='etapas')renderStages()}
function showApp(){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');load()}
function showLogin(){$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden')}
async function load(){if(demo){projects=demoProjects.map(x=>({...x}));setStatus('Modo demo',true);render();return}try{projects=await api('/proyectos');setStatus('API conectada',true);render()}catch(e){projects=[];setStatus('API sin conexión',false);render()}}
function setStatus(t,ok){$('#apiStatus').textContent=t;$('#apiStatus').previousElementSibling.style.background=ok?'#35b779':'#f0ad4e'}
function render(){let avg=projects.length?Math.round(projects.reduce((a,p)=>a+(p.progreso||0),0)/projects.length):0;$('#nProjects').textContent=projects.length;$('#nActive').textContent=projects.filter(p=>p.estado==='EN_PROCESO').length;$('#nDone').textContent=projects.filter(p=>p.estado==='FINALIZADO').length;$('#nAvg').textContent=avg+'%';$('#dashProjects').innerHTML=projects.slice(0,3).map(card).join('')||'<div class="empty"><h3>No hay proyectos</h3><p>Crea tu primer proyecto.</p></div>';$('#projectList').innerHTML=projects.map(row).join('')||'<div class="empty"><h3>No hay proyectos</h3><p>Crea tu primer proyecto.</p></div>'}
function card(p){return `<article class="card"><span class="tag">${esc(p.estado||'BORRADOR')}</span><h3>${esc(p.titulo)}</h3><p>${esc(p.descripcion||p.problemaInicial||'Sin descripción')}</p><div class="progress"><i style="width:${p.progreso||0}%"></i></div><small>${p.progreso||0}% completado</small></article>`}
function row(p){return `<article class="row"><div><h3>${esc(p.titulo)}</h3><p>${esc(p.problemaInicial||p.descripcion||'')}</p></div><div><div class="progress"><i style="width:${p.progreso||0}%"></i></div><small>${p.progreso||0}%</small></div><span class="status ${p.estado==='EN_PROCESO'?'active':''}">${esc(p.estado||'BORRADOR')}</span></article>`}
function renderStages(){if(!projects.length){$('#stageArea').innerHTML='<div class="empty"><h3>No hay proyectos</h3><p>Crea un proyecto para comenzar.</p></div>';return}let opts=projects.map(p=>`<option value="${p.id}">${esc(p.titulo)}</option>`).join('');$('#stageArea').innerHTML=`<div class="stage-select">Proyecto: <select id="stageProject">${opts}</select></div><div id="stages" class="stages"></div>`;$('#stageProject').onchange=renderSelected;renderSelected()}
function renderSelected(){let p=projects.find(x=>String(x.id)===$('#stageProject').value)||projects[0];$('#stages').innerHTML=stages.map((s,i)=>{let v=Math.max(0,Math.min(100,Math.round((p.progreso||0)-i*25)));return `<article class="stage"><div class="num">${i+1}</div><h3>${s[0]}</h3><p>${s[1]}</p><div class="progress"><i style="width:${v}%"></i></div><small>${v}% completado</small></article>`}).join('')}
function openModal(){$('#modal').classList.remove('hidden');$('#pTitle').focus()}function closeModal(){$('#modal').classList.add('hidden');$('#projectForm').reset();$('#teamId').value=1}
async function create(e){e.preventDefault();$('#projectMsg').textContent='';let p={titulo:$('#pTitle').value,descripcion:$('#pDesc').value,problemaInicial:$('#pProblem').value,equipoId:+$('#teamId').value,estado:'BORRADOR',progreso:0};if(demo){projects.unshift({id:Date.now(),...p});closeModal();render();return}try{await api('/proyectos',{method:'POST',body:JSON.stringify(p)});closeModal();load()}catch(e){$('#projectMsg').textContent='No se pudo crear el proyecto.'}}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]) )}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{let x=await api('/auth/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});token=x.token;localStorage.setItem('dt_token',token);demo=false;localStorage.removeItem('dt_demo');showApp()}catch(e){$('#loginMsg').textContent='Usuario o contraseña incorrectos.'}};
$('#demoBtn').onclick=()=>{demo=true;localStorage.setItem('dt_demo','true');showApp()};$('#logout').onclick=()=>{token='';demo=false;localStorage.clear();showLogin()};$('#refresh').onclick=load;$('#new1').onclick=openModal;$('#new2').onclick=openModal;$('#close').onclick=closeModal;$('#cancel').onclick=closeModal;$('#projectForm').onsubmit=create;document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>section(b.dataset.section));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>section(b.dataset.go));if(token||demo)showApp();
